version: 0.2
phases:
  install:
    runtime-versions:
      java: correto11
  build:
    commands:
      - echo "Fase de build começando..."
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo "Pipeline sucesso"
